apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://localhost:8086
    secureJsonData:
      token: my-token
    jsonData:
      version: Flux
      organization: my-org
      defaultBucket: my-bucket
      tlsSkipVerify: true
